# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Download Newspaper Test

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 4 * * *"
#  pull_request:
#    branches: [ master ]

env:
  TZ: Asia/Shanghai
jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install requests
    - name: Producing Newspaper...
      run: |
        mkdir ./Newspaper
        sudo mv /etc/ImageMagick-6/policy.xml /etc/ImageMagick-6/policy.xml.off
        date '+%c'
        python ./download_globaltimes.py
        sudo mv /etc/ImageMagick-6/policy.xml.off /etc/ImageMagick-6/policy.xml
#    - name: Rcloing to cloud...
#      uses: wei/rclone@v1.1.1
#      env:
#        RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
#      with:
#        args: copy /home/runner/work/download_newspaper/download_newspaper/Newspaper/ 1drv:NewsPaper
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Produced PDF
        path: ./Newspaper/
