# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Download Newspaper Test

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

env:
  TZ: Asia/Shanghai
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Producing Newspaper...
      run: |
        mkdir -p /home/haroldw-3141/test/Newspaper/
        cd download_newspaper
        python ./download_globaltimes.py
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Produced PDF
        path: /home/haroldw-3141/test/Newspaper/
